function [xyz_from_guess_index, voxel_count_from_guess_index, sqrt_condition_number_from_guess_index, max_intensity_from_guess_index] = ...
    find_somata_in_uint16_stack(padded_stack_yxz, ...
                                padded_origin_xyz, ...
                                spacing_xyz, ...
                                origin_xyz, ...
                                shape_xyz, ...
                                parameters)
   
    % Get candidate blobs and their features                        
    [voxel_count_from_candidate_index, ...
     xyz_from_candidate_index, ...
     sqrt_condition_number_from_candidate_index, ...
     max_intensity_from_candidate_index] = ...
        compute_somalike_features_in_uint16_stack(padded_stack_yxz, ...
                                                  padded_origin_xyz, ...
                                                  spacing_xyz, ...
                                                  origin_xyz, ...
                                                  shape_xyz, ...
                                                  parameters) ;   

    % Use feature cutoffs to winnow candidates down to "guesses"                                          
    minimum_volume = parameters.minimum_volume ;
    maximum_volume = parameters.maximum_volume ;
    maximum_sqrt_condition_number = parameters.maximum_sqrt_condition_number ;     
    volume_per_voxel = prod(spacing_xyz) ;
    minimum_volume_in_voxels = minimum_volume / volume_per_voxel ;
    maximum_volume_in_voxels = maximum_volume / volume_per_voxel ;
    is_guess_from_candidate_index = ...
        (minimum_volume_in_voxels < voxel_count_from_candidate_index) & ...
        (voxel_count_from_candidate_index < maximum_volume_in_voxels) & ...
        sqrt_condition_number_from_candidate_index < maximum_sqrt_condition_number ;
    xyz_from_guess_index = xyz_from_candidate_index(is_guess_from_candidate_index, :) ;    
    voxel_count_from_guess_index = voxel_count_from_candidate_index(is_guess_from_candidate_index) ;
    sqrt_condition_number_from_guess_index =sqrt_condition_number_from_candidate_index(is_guess_from_candidate_index) ;
    max_intensity_from_guess_index = max_intensity_from_candidate_index(is_guess_from_candidate_index) ;                                              
end
