function pad_and_find_somata_then_save(somata_mat_file_path, ...
                                       rendered_folder_path, ...
                                       gfp_channel_index, ...
                                       zoom_level, ...
                                       spacing_at_zoom_level_xyz, ...
                                       origin_at_zoom_level_xyz, ...
                                       substack_origin_ijk1, ...
                                       substack_shape_ijk, ...
                                       pad_depth_in_um, ...
                                       parameters)

    [xyz_from_guess_index, ..., ...
     voxel_count_from_guess_index, ...
     sqrt_condition_number_from_guess_index, ...
     max_intensity_from_guess_index] = ...
        pad_and_find_somata(rendered_folder_path, ...
                            gfp_channel_index, ...
                            zoom_level, ...
                            spacing_at_zoom_level_xyz, ...
                            origin_at_zoom_level_xyz, ...
                            substack_origin_ijk1, ...
                            substack_shape_ijk, ...
                            pad_depth_in_um, ...
                            parameters) ;
   save(somata_mat_file_path, ...
        'xyz_from_guess_index', ...
        'voxel_count_from_guess_index', ...
        'sqrt_condition_number_from_guess_index', ...
        'max_intensity_from_guess_index') ;
end
