function pad_and_find_candidate_somata_then_save(somata_mat_file_path, ...
                                                 rendered_folder_path, ...
                                                 gfp_channel_index, ...
                                                 zoom_level, ...
                                                 spacing_at_zoom_level_xyz, ...
                                                 origin_at_zoom_level_xyz, ...
                                                 substack_origin_ijk1, ...
                                                 substack_shape_ijk, ...
                                                 pad_depth_in_um, ...
                                                 parameters)

    [xyz_from_candidate_index, feature_struct_from_candidate_index] = ...
        pad_and_find_candidate_somata(rendered_folder_path, ...
                                      gfp_channel_index, ...
                                      zoom_level, ...
                                      spacing_at_zoom_level_xyz, ...
                                      origin_at_zoom_level_xyz, ...
                                      substack_origin_ijk1, ...
                                      substack_shape_ijk, ...
                                      pad_depth_in_um, ...
                                      parameters) ;
   save(somata_mat_file_path, ...
        'xyz_from_candidate_index', 'feature_struct_from_candidate_index') ;
end
